# statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: keretdodor/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-cred
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-cred
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_HOST           
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_ROOT_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
        volumeMounts:            
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      storageClassName: "manual" 
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi 

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP  
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql