
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 2Gi
  hostPath:
    path: /mysql1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 2Gi
  hostPath:
    path: /mysql2